[package]
name = "lexo_corpus"
version = "0.1.0"
edition = "2021"

[lib]
name = "lexocorpus"
crate-type = ["cdylib"]

[dependencies]
pdf-extract = "0.8.0"
linregress = "0.5.4"
plotters = "0.3.3"
csv = "1.3.1"
lopdf = "0.35.0"
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }